deployment:
  tasks:
    - export DEPLOYPATH=/home/teasucom/nodejsapp
    - /bin/mkdir $DEPLOYPATH
    - /bin/cp src/App.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp script.sh $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH/tmp
    - cd $DEPLOYPATH
    - /bin/sh npm install
    - /bin/sh npm run start
