deployment:
  tasks:
    - export DEPLOYPATH=/home/teasucom/public_html
    - /bin/cp src/App.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp script.sh $DEPLOYPATH
    - /bin/mkdir $DEPLOYPATH/tmp
    - cd $DEPLOYPATH
    - /bin/sh npm install
    - /bin/sh npm run start

on:
  push:
    branches:
      - main
name: Deploy website on push

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Sync files
        uses: /home/teasucom/public_html
